static const luasodium_constant_t ls_crypto_stream_constants[] = {
    LS_CONST_PTR(crypto_stream_KEYBYTES,crypto_stream_keybytes,1),
    LS_CONST_PTR(crypto_stream_NONCEBYTES,crypto_stream_noncebytes,1),
    LS_CONST_PTR(crypto_stream_xsalsa20_KEYBYTES,crypto_stream_xsalsa20_keybytes,1),
    LS_CONST_PTR(crypto_stream_xsalsa20_NONCEBYTES,crypto_stream_xsalsa20_noncebytes,1),
    LS_CONST_PTR(crypto_stream_salsa20_KEYBYTES,crypto_stream_salsa20_keybytes,1),
    LS_CONST_PTR(crypto_stream_salsa20_NONCEBYTES,crypto_stream_salsa20_noncebytes,1),
    LS_CONST_PTR(crypto_stream_salsa2012_KEYBYTES,crypto_stream_salsa2012_keybytes,1),
    LS_CONST_PTR(crypto_stream_salsa2012_NONCEBYTES,crypto_stream_salsa2012_noncebytes,1),
    LS_CONST_PTR(crypto_stream_salsa208_KEYBYTES,crypto_stream_salsa208_keybytes,1),
    LS_CONST_PTR(crypto_stream_salsa208_NONCEBYTES,crypto_stream_salsa208_noncebytes,1),
    LS_CONST_PTR(crypto_stream_chacha20_KEYBYTES,crypto_stream_chacha20_keybytes,1),
    LS_CONST_PTR(crypto_stream_chacha20_NONCEBYTES,crypto_stream_chacha20_noncebytes,1),
    LS_CONST_PTR(crypto_stream_chacha20_ietf_KEYBYTES,crypto_stream_chacha20_ietf_keybytes,1),
    LS_CONST_PTR(crypto_stream_chacha20_ietf_NONCEBYTES,crypto_stream_chacha20_ietf_noncebytes,1),
    LS_CONST_PTR(crypto_stream_xchacha20_KEYBYTES,crypto_stream_xchacha20_keybytes,1),
    LS_CONST_PTR(crypto_stream_xchacha20_NONCEBYTES,crypto_stream_xchacha20_noncebytes,1),
    { NULL, 0, 0 },
};

