#define STR(x) #x
#define XSTR(x) STR(x)

#define LUASODIUM_VERSION_MAJOR 2
#define LUASODIUM_VERSION_MINOR 2
#define LUASODIUM_VERSION_PATCH 0
#define LUASODIUM_VERSION XSTR(LUASODIUM_VERSION_MAJOR) "." XSTR(LUASODIUM_VERSION_MINOR) "." XSTR(LUASODIUM_VERSION_PATCH)

static const luasodium_constant_t ls_version_constants[] = {
    { "_VERSION_MAJOR", LUASODIUM_VERSION_MAJOR },
    { "_VERSION_MINOR", LUASODIUM_VERSION_MINOR },
    { "_VERSION_PATCH", LUASODIUM_VERSION_PATCH },
    { NULL, 0},
};

